-- FASE 1 - SCHEMA V2 CANÔNICO (100% módulos)

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  CREATE TYPE public.app_role AS ENUM ('USUARIO', 'ADMIN', 'MASTER_TI', 'SYSTEM_OWNER');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Empresas e acesso
CREATE TABLE IF NOT EXISTS public.empresas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  slug text UNIQUE,
  cnpj text,
  status text NOT NULL DEFAULT 'active',
  plano text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY,
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  nome text NOT NULL,
  email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, empresa_id, role)
);

-- Cadastros base
CREATE TABLE IF NOT EXISTS public.plantas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  codigo text NOT NULL,
  nome text NOT NULL,
  descricao text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, codigo)
);

CREATE TABLE IF NOT EXISTS public.areas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  planta_id uuid NOT NULL REFERENCES public.plantas(id) ON DELETE CASCADE,
  codigo text NOT NULL,
  nome text NOT NULL,
  descricao text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, planta_id, codigo)
);

CREATE TABLE IF NOT EXISTS public.sistemas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  area_id uuid NOT NULL REFERENCES public.areas(id) ON DELETE CASCADE,
  codigo text NOT NULL,
  nome text NOT NULL,
  descricao text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, area_id, codigo)
);

CREATE TABLE IF NOT EXISTS public.equipamentos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  sistema_id uuid REFERENCES public.sistemas(id) ON DELETE SET NULL,
  tag text NOT NULL,
  nome text NOT NULL,
  criticidade text DEFAULT 'C' NOT NULL,
  nivel_risco text DEFAULT 'BAIXO' NOT NULL,
  localizacao text,
  fabricante text,
  modelo text,
  numero_serie text,
  data_instalacao date,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, tag)
);

CREATE TABLE IF NOT EXISTS public.componentes_equipamento (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  equipamento_id uuid NOT NULL REFERENCES public.equipamentos(id) ON DELETE CASCADE,
  nome text NOT NULL,
  descricao text,
  criticidade text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- OS e execução
CREATE TABLE IF NOT EXISTS public.ordens_servico (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  numero_os bigint GENERATED BY DEFAULT AS IDENTITY,
  tipo text NOT NULL,
  prioridade text NOT NULL,
  status text NOT NULL,
  tag text,
  equipamento text,
  problema text,
  solicitante text,
  usuario_abertura uuid,
  tempo_estimado integer,
  data_solicitacao timestamptz NOT NULL DEFAULT now(),
  data_fechamento timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mecanicos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  nome text NOT NULL,
  tipo text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.execucoes_os (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  os_id uuid NOT NULL REFERENCES public.ordens_servico(id) ON DELETE CASCADE,
  mecanico_id uuid REFERENCES public.mecanicos(id),
  mecanico_nome text,
  hora_inicio time,
  hora_fim time,
  tempo_execucao integer,
  servico_executado text,
  custo_mao_obra numeric(12,2) DEFAULT 0,
  custo_materiais numeric(12,2) DEFAULT 0,
  custo_terceiros numeric(12,2) DEFAULT 0,
  custo_total numeric(12,2) DEFAULT 0,
  data_execucao date,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.materiais (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  codigo text NOT NULL,
  nome text NOT NULL,
  unidade text,
  estoque_atual numeric(14,4) DEFAULT 0,
  estoque_minimo numeric(14,4) DEFAULT 0,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, codigo)
);

CREATE TABLE IF NOT EXISTS public.materiais_os (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  os_id uuid NOT NULL REFERENCES public.ordens_servico(id) ON DELETE CASCADE,
  material_id uuid NOT NULL REFERENCES public.materiais(id) ON DELETE CASCADE,
  quantidade numeric(14,4) NOT NULL DEFAULT 0,
  custo_unitario numeric(12,2) DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.movimentacoes_materiais (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  material_id uuid NOT NULL REFERENCES public.materiais(id) ON DELETE CASCADE,
  os_id uuid REFERENCES public.ordens_servico(id) ON DELETE SET NULL,
  tipo_movimentacao text NOT NULL,
  quantidade numeric(14,4) NOT NULL,
  custo_unitario numeric(12,2),
  usuario_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Preventiva
CREATE TABLE IF NOT EXISTS public.planos_preventivos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  equipamento_id uuid REFERENCES public.equipamentos(id) ON DELETE SET NULL,
  codigo text NOT NULL,
  nome text NOT NULL,
  descricao text,
  tag text,
  tipo_gatilho text,
  frequencia_dias integer,
  frequencia_ciclos integer,
  condicao_disparo text,
  ultima_execucao timestamptz,
  proxima_execucao timestamptz,
  tempo_estimado_min integer,
  especialidade text,
  instrucoes text,
  checklist jsonb DEFAULT '[]'::jsonb,
  materiais_previstos jsonb DEFAULT '[]'::jsonb,
  responsavel_nome text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, codigo)
);

CREATE TABLE IF NOT EXISTS public.atividades_preventivas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  plano_id uuid NOT NULL REFERENCES public.planos_preventivos(id) ON DELETE CASCADE,
  nome text NOT NULL,
  responsavel text,
  ordem integer NOT NULL DEFAULT 1,
  tempo_total_min integer NOT NULL DEFAULT 0,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.servicos_preventivos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  atividade_id uuid NOT NULL REFERENCES public.atividades_preventivas(id) ON DELETE CASCADE,
  descricao text NOT NULL,
  tempo_estimado_min integer NOT NULL DEFAULT 0,
  ordem integer NOT NULL DEFAULT 1,
  concluido boolean NOT NULL DEFAULT false,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.templates_preventivos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  nome text NOT NULL,
  descricao text,
  estrutura jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.execucoes_preventivas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  plano_id uuid NOT NULL REFERENCES public.planos_preventivos(id) ON DELETE CASCADE,
  executor_nome text NOT NULL,
  executor_id uuid,
  data_execucao timestamptz NOT NULL DEFAULT now(),
  tempo_real_min integer,
  status text,
  checklist jsonb DEFAULT '[]'::jsonb,
  observacoes text,
  os_gerada_id uuid REFERENCES public.ordens_servico(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Lubrificação
CREATE TABLE IF NOT EXISTS public.planos_lubrificacao (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  equipamento_id uuid REFERENCES public.equipamentos(id) ON DELETE SET NULL,
  codigo text NOT NULL,
  nome text NOT NULL,
  descricao text,
  ponto_lubrificacao text,
  lubrificante text,
  periodicidade integer,
  tipo_periodicidade text,
  proxima_execucao timestamptz,
  ultima_execucao timestamptz,
  tempo_estimado integer,
  prioridade text,
  status text,
  responsavel_nome text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, codigo)
);

CREATE TABLE IF NOT EXISTS public.atividades_lubrificacao (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  plano_id uuid NOT NULL REFERENCES public.planos_lubrificacao(id) ON DELETE CASCADE,
  nome text NOT NULL,
  ordem integer NOT NULL DEFAULT 1,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.execucoes_lubrificacao (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  plano_id uuid NOT NULL REFERENCES public.planos_lubrificacao(id) ON DELETE CASCADE,
  executor_nome text NOT NULL,
  data_execucao timestamptz NOT NULL DEFAULT now(),
  status text,
  observacoes text,
  os_gerada_id uuid REFERENCES public.ordens_servico(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Preditiva / Inspeção / Eng. confiabilidade
CREATE TABLE IF NOT EXISTS public.medicoes_preditivas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  equipamento_id uuid REFERENCES public.equipamentos(id) ON DELETE SET NULL,
  tag text,
  tipo_medicao text,
  valor numeric(14,4),
  limite_alerta numeric(14,4),
  limite_critico numeric(14,4),
  status text,
  observacoes text,
  responsavel_nome text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inspecoes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  numero_inspecao text,
  rota_nome text,
  descricao text,
  data_inspecao date,
  status text,
  inspetor_id uuid,
  inspetor_nome text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.anomalias_inspecao (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  inspecao_id uuid NOT NULL REFERENCES public.inspecoes(id) ON DELETE CASCADE,
  descricao text,
  criticidade text,
  status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.fmea (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  equipamento_id uuid REFERENCES public.equipamentos(id),
  modo_falha text,
  efeito text,
  causa text,
  severidade integer,
  ocorrencia integer,
  deteccao integer,
  rpn integer,
  status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.analise_causa_raiz (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  os_id uuid REFERENCES public.ordens_servico(id) ON DELETE SET NULL,
  problema text,
  causa_raiz text,
  metodologia text,
  status text,
  preventive_actions jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.acoes_corretivas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  rca_id uuid REFERENCES public.analise_causa_raiz(id) ON DELETE CASCADE,
  descricao text,
  responsavel text,
  prazo date,
  status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.melhorias (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  equipamento_id uuid REFERENCES public.equipamentos(id) ON DELETE SET NULL,
  titulo text,
  descricao text,
  status text,
  ganho_estimado numeric(12,2),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Suprimentos / contratos / ssma
CREATE TABLE IF NOT EXISTS public.fornecedores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  nome text NOT NULL,
  cnpj text,
  contato text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.contratos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  fornecedor_id uuid NOT NULL REFERENCES public.fornecedores(id) ON DELETE CASCADE,
  numero text,
  descricao text,
  valor numeric(14,2),
  data_inicio date,
  data_fim date,
  status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.avaliacoes_fornecedores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  contrato_id uuid NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  nota numeric(5,2),
  comentario text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.permissoes_trabalho (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  os_id uuid REFERENCES public.ordens_servico(id) ON DELETE SET NULL,
  numero text,
  status text,
  riscos_identificados text,
  medidas_controle text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.incidentes_ssma (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  rca_id uuid REFERENCES public.analise_causa_raiz(id) ON DELETE SET NULL,
  descricao text,
  gravidade text,
  status text,
  data_incidente timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Config / docs / sequências
CREATE TABLE IF NOT EXISTS public.documentos_tecnicos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  equipamento_id uuid REFERENCES public.equipamentos(id) ON DELETE SET NULL,
  titulo text NOT NULL,
  tipo text,
  arquivo_url text,
  revisao text,
  status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.configuracoes_sistema (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  chave text NOT NULL,
  valor jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, chave)
);

CREATE TABLE IF NOT EXISTS public.dados_empresa (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id) UNIQUE,
  razao_social text,
  nome_fantasia text,
  cnpj text,
  logo_url text,
  logo_os_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.document_sequences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  tipo_documento text NOT NULL,
  prefixo text NOT NULL,
  proximo_numero bigint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, tipo_documento)
);

CREATE TABLE IF NOT EXISTS public.document_layouts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  tipo_documento text NOT NULL,
  versao text NOT NULL,
  nome text,
  configuracao jsonb NOT NULL DEFAULT '{}'::jsonb,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Permissões granulares / segurança / rate-limit
CREATE TABLE IF NOT EXISTS public.permissoes_granulares (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  user_id uuid NOT NULL,
  modulo text NOT NULL,
  visualizar boolean DEFAULT false,
  criar boolean DEFAULT false,
  editar boolean DEFAULT false,
  excluir boolean DEFAULT false,
  alterar_status boolean DEFAULT false,
  imprimir boolean DEFAULT false,
  exportar boolean DEFAULT false,
  importar boolean DEFAULT false,
  acessar_indicadores boolean DEFAULT false,
  acessar_historico boolean DEFAULT false,
  ver_valores boolean DEFAULT false,
  ver_custos boolean DEFAULT false,
  ver_criticidade boolean DEFAULT false,
  ver_status boolean DEFAULT false,
  ver_obs_internas boolean DEFAULT false,
  ver_dados_financeiros boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, user_id, modulo)
);

CREATE TABLE IF NOT EXISTS public.security_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid REFERENCES public.empresas(id),
  actor_user_id uuid,
  actor_email text,
  event_type text NOT NULL,
  severity text NOT NULL DEFAULT 'info',
  source text NOT NULL DEFAULT 'app',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.rate_limits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid REFERENCES public.empresas(id),
  key text NOT NULL,
  hits integer NOT NULL DEFAULT 0,
  window_started_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (empresa_id, key)
);

-- Agenda única
CREATE TABLE IF NOT EXISTS public.maintenance_schedule (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  tipo text NOT NULL CHECK (tipo IN ('preventiva', 'lubrificacao', 'inspecao', 'preditiva')),
  origem_id uuid NOT NULL,
  equipamento_id uuid REFERENCES public.equipamentos(id) ON DELETE SET NULL,
  titulo text NOT NULL,
  descricao text,
  data_programada timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'programado',
  responsavel text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tipo, origem_id)
);

-- Auditoria unificada
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid REFERENCES public.empresas(id),
  action text NOT NULL,
  table_name text NOT NULL,
  record_id text,
  source text NOT NULL DEFAULT 'app',
  severity text NOT NULL DEFAULT 'info',
  actor_user_id uuid,
  actor_email text,
  correlation_id uuid DEFAULT gen_random_uuid(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.enterprise_audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid REFERENCES public.empresas(id),
  table_name text,
  operation text,
  record_id text,
  actor_id uuid,
  action_type text,
  severity text NOT NULL DEFAULT 'info',
  source text NOT NULL DEFAULT 'system',
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Índices úteis
CREATE INDEX IF NOT EXISTS idx_ordens_servico_empresa_status ON public.ordens_servico (empresa_id, status);
CREATE INDEX IF NOT EXISTS idx_planos_preventivos_empresa_proxima ON public.planos_preventivos (empresa_id, proxima_execucao);
CREATE INDEX IF NOT EXISTS idx_planos_lubrificacao_empresa_proxima ON public.planos_lubrificacao (empresa_id, proxima_execucao);
CREATE INDEX IF NOT EXISTS idx_medicoes_preditivas_empresa_status ON public.medicoes_preditivas (empresa_id, status);
CREATE INDEX IF NOT EXISTS idx_maintenance_schedule_empresa_data ON public.maintenance_schedule (empresa_id, data_programada);
CREATE INDEX IF NOT EXISTS idx_audit_logs_empresa_created ON public.audit_logs (empresa_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_enterprise_audit_logs_empresa_created ON public.enterprise_audit_logs (empresa_id, created_at DESC);

COMMIT;
