begin;

create extension if not exists pgcrypto;

-- ============================================================
-- Helpers
-- ============================================================
create or replace function public.tg_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.ensure_updated_at_trigger(p_table regclass)
returns void
language plpgsql
as $$
declare
  trigger_name text := 'trg_' || replace(p_table::text, '.', '_') || '_updated_at';
begin
  execute format('drop trigger if exists %I on %s', trigger_name, p_table);
  execute format('create trigger %I before update on %s for each row execute function public.tg_set_updated_at()', trigger_name, p_table);
exception when others then
  raise notice 'Falha ao criar trigger updated_at em %: %', p_table::text, sqlerrm;
end;
$$;

-- ============================================================
-- Tabelas base de tenancy/acesso usadas pelo frontend
-- ============================================================
create table if not exists public.empresas (
  id uuid primary key default gen_random_uuid(),
  nome text,
  dominio text,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.empresa_config (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid,
  nome_empresa text,
  logo_url text,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.profiles (
  id uuid primary key,
  nome text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  role text,
  created_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  action text,
  details jsonb,
  created_at timestamptz default now()
);

create table if not exists public.enterprise_audit_logs (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid,
  user_id uuid,
  action text,
  details jsonb,
  created_at timestamptz default now()
);

create table if not exists public.security_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  action text,
  success boolean,
  metadata jsonb,
  created_at timestamptz default now()
);

-- ============================================================
-- Hierarquia / equipamentos
-- ============================================================
create table if not exists public.plantas (
  id uuid primary key default gen_random_uuid(),
  codigo text,
  nome text,
  endereco text,
  responsavel text,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.areas (
  id uuid primary key default gen_random_uuid(),
  planta_id uuid,
  codigo text,
  nome text,
  descricao text,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.sistemas (
  id uuid primary key default gen_random_uuid(),
  area_id uuid,
  codigo text,
  nome text,
  descricao text,
  funcao_principal text,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.equipamentos (
  id uuid primary key default gen_random_uuid(),
  sistema_id uuid,
  tag text,
  nome text,
  criticidade text,
  nivel_risco text,
  localizacao text,
  fabricante text,
  modelo text,
  numero_serie text,
  data_instalacao date,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.equipamentos add column if not exists sistema_id uuid;
alter table public.equipamentos add column if not exists criticidade text;
alter table public.equipamentos add column if not exists nivel_risco text;

-- ============================================================
-- Ordens / solicitações / execução
-- ============================================================
create table if not exists public.ordens_servico (
  id uuid primary key default gen_random_uuid(),
  numero_os bigint generated by default as identity,
  tipo text,
  prioridade text,
  tag text,
  equipamento text,
  solicitante text,
  problema text,
  status text default 'ABERTA',
  data_solicitacao timestamptz default now(),
  data_fechamento timestamptz,
  tempo_estimado numeric,
  modo_falha text,
  causa_raiz text,
  acao_corretiva text,
  licoes_aprendidas text,
  usuario_abertura uuid,
  usuario_fechamento uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.execucoes_os (
  id uuid primary key default gen_random_uuid(),
  os_id uuid,
  mecanico_id uuid,
  mecanico_nome text,
  data_execucao date default current_date,
  hora_inicio text,
  hora_fim text,
  tempo_execucao numeric,
  servico_executado text,
  custo_mao_obra numeric,
  custo_materiais numeric,
  custo_terceiros numeric,
  custo_total numeric,
  created_at timestamptz default now()
);

create table if not exists public.solicitacoes_manutencao (
  id uuid primary key default gen_random_uuid(),
  numero_solicitacao bigint generated by default as identity,
  equipamento_id uuid,
  tag text,
  solicitante_nome text,
  solicitante_setor text,
  descricao_falha text,
  impacto text,
  classificacao text,
  status text default 'PENDENTE',
  os_id uuid,
  sla_horas integer,
  data_limite timestamptz,
  observacoes text,
  data_aprovacao timestamptz,
  usuario_aprovacao uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Tabela de compatibilidade legada para ambientes antigos
create table if not exists public.solicitacoes (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  equipamento_id uuid,
  tag text,
  solicitante text,
  solicitante_setor text,
  descricao text,
  impacto text,
  classificacao text,
  status text default 'PENDENTE',
  os_id uuid,
  sla_horas integer,
  data_limite timestamptz,
  observacoes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================
-- Módulos que apresentaram erro de coluna
-- ============================================================
create table if not exists public.mecanicos (
  id uuid primary key default gen_random_uuid(),
  nome text,
  telefone text,
  tipo text,
  especialidade text,
  custo_hora numeric,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.mecanicos add column if not exists custo_hora numeric;

create table if not exists public.materiais (
  id uuid primary key default gen_random_uuid(),
  codigo text,
  nome text,
  unidade text,
  custo_unitario numeric default 0,
  estoque_atual numeric default 0,
  estoque_minimo numeric default 0,
  localizacao text,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.materiais add column if not exists custo_unitario numeric default 0;

create table if not exists public.movimentacoes_materiais (
  id uuid primary key default gen_random_uuid(),
  material_id uuid,
  os_id uuid,
  tipo text,
  quantidade numeric,
  custo_unitario numeric,
  custo_total numeric,
  observacao text,
  usuario_id uuid,
  usuario_nome text,
  created_at timestamptz default now()
);

create table if not exists public.materiais_os (
  id uuid primary key default gen_random_uuid(),
  os_id uuid,
  material_id uuid,
  quantidade numeric,
  custo_unitario numeric,
  custo_total numeric,
  created_at timestamptz default now()
);

create table if not exists public.fornecedores (
  id uuid primary key default gen_random_uuid(),
  codigo text,
  razao_social text,
  nome_fantasia text,
  cnpj text,
  tipo text,
  especialidade text,
  telefone text,
  email text,
  endereco text,
  contato_nome text,
  contato_telefone text,
  avaliacao_media numeric,
  total_avaliacoes integer,
  ativo boolean default true,
  observacoes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.fornecedores add column if not exists codigo text;

create table if not exists public.contratos (
  id uuid primary key default gen_random_uuid(),
  numero_contrato text,
  fornecedor_id uuid,
  titulo text,
  descricao text,
  tipo text,
  valor_total numeric,
  valor_mensal numeric,
  data_inicio date,
  data_fim date,
  sla_atendimento_horas integer,
  sla_resolucao_horas integer,
  penalidade_descricao text,
  status text,
  responsavel_nome text,
  responsavel_id uuid,
  anexos jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================
-- Preventiva / lubrificação / programação
-- ============================================================
create table if not exists public.planos_preventivos (
  id uuid primary key default gen_random_uuid(),
  codigo text,
  nome text,
  descricao text,
  equipamento_id uuid,
  tag text,
  tipo_gatilho text,
  frequencia_dias integer,
  frequencia_ciclos integer,
  condicao_disparo text,
  ultima_execucao timestamptz,
  proxima_execucao timestamptz,
  tempo_estimado_min integer,
  especialidade text,
  instrucoes text,
  checklist jsonb,
  materiais_previstos jsonb,
  responsavel_nome text,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.atividades_preventivas (
  id uuid primary key default gen_random_uuid(),
  plano_id uuid,
  nome text,
  responsavel text,
  ordem integer,
  tempo_total_min integer default 0,
  observacoes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.servicos_preventivos (
  id uuid primary key default gen_random_uuid(),
  atividade_id uuid,
  descricao text,
  tempo_estimado_min integer,
  ordem integer,
  concluido boolean default false,
  observacoes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.execucoes_preventivas (
  id uuid primary key default gen_random_uuid(),
  plano_id uuid,
  executor_nome text,
  executor_id uuid,
  data_execucao timestamptz default now(),
  tempo_real_min integer,
  status text,
  checklist jsonb,
  observacoes text,
  os_gerada_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.templates_preventivos (
  id uuid primary key default gen_random_uuid(),
  nome text,
  descricao text,
  estrutura jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.planos_lubrificacao (
  id uuid primary key default gen_random_uuid(),
  codigo text,
  nome text,
  equipamento_id uuid,
  tag text,
  periodicidade_dias integer,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.atividades_lubrificacao (
  id uuid primary key default gen_random_uuid(),
  plano_id uuid,
  ordem integer,
  descricao text,
  ponto_lubrificacao text,
  lubrificante text,
  quantidade numeric,
  observacoes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.execucoes_lubrificacao (
  id uuid primary key default gen_random_uuid(),
  plano_id uuid,
  executor_nome text,
  data_execucao timestamptz default now(),
  observacoes text,
  os_gerada_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.maintenance_schedule (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid,
  tipo text,
  origem_id uuid,
  equipamento_id uuid,
  titulo text,
  descricao text,
  data_programada timestamptz,
  status text default 'programado',
  responsavel text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists ux_maintenance_schedule_tipo_origem
  on public.maintenance_schedule(tipo, origem_id);

-- ============================================================
-- Preditiva / inspeções / SSMA / RCA / melhorias / docs
-- ============================================================
create table if not exists public.medicoes_preditivas (
  id uuid primary key default gen_random_uuid(),
  equipamento_id uuid,
  tag text,
  tipo_medicao text,
  valor numeric,
  unidade text,
  limite_alerta numeric,
  limite_critico numeric,
  status text,
  observacoes text,
  responsavel_id uuid,
  responsavel_nome text,
  os_gerada_id uuid,
  created_at timestamptz default now()
);

create table if not exists public.inspecoes (
  id uuid primary key default gen_random_uuid(),
  numero_inspecao bigint generated by default as identity,
  rota_nome text,
  descricao text,
  turno text,
  inspetor_nome text,
  inspetor_id uuid,
  data_inspecao date,
  hora_inicio text,
  hora_fim text,
  status text,
  itens_inspecionados jsonb,
  anomalias_encontradas integer,
  observacoes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.anomalias_inspecao (
  id uuid primary key default gen_random_uuid(),
  inspecao_id uuid,
  equipamento_id uuid,
  tag text,
  descricao text,
  severidade text,
  foto_url text,
  os_gerada_id uuid,
  status text,
  created_at timestamptz default now()
);

create table if not exists public.permissoes_trabalho (
  id uuid primary key default gen_random_uuid(),
  numero_pt bigint generated by default as identity,
  os_id uuid,
  equipamento_id uuid,
  tag text,
  tipo text,
  descricao_servico text,
  riscos_identificados text,
  medidas_controle text,
  epis_requeridos text,
  isolamentos text,
  data_inicio timestamptz,
  data_fim timestamptz,
  executante_nome text,
  supervisor_nome text,
  aprovador_nome text,
  aprovador_id uuid,
  status text,
  checklist_seguranca jsonb,
  observacoes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.incidentes_ssma (
  id uuid primary key default gen_random_uuid(),
  numero_incidente bigint generated by default as identity,
  tipo text,
  severidade text,
  data_ocorrencia timestamptz,
  local_ocorrencia text,
  equipamento_id uuid,
  tag text,
  descricao text,
  pessoas_envolvidas text,
  testemunhas text,
  causas_imediatas text,
  causas_basicas text,
  acoes_imediatas text,
  rca_id uuid,
  dias_afastamento integer,
  custo_estimado numeric,
  status text,
  responsavel_nome text,
  responsavel_id uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.fmea (
  id uuid primary key default gen_random_uuid(),
  equipamento_id uuid,
  tag text,
  funcao text,
  falha_funcional text,
  modo_falha text,
  efeito_falha text,
  causa_falha text,
  severidade integer,
  ocorrencia integer,
  deteccao integer,
  rpn integer,
  acao_recomendada text,
  responsavel text,
  prazo date,
  status text,
  plano_preventivo_id uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.analise_causa_raiz (
  id uuid primary key default gen_random_uuid(),
  numero_rca bigint generated by default as identity,
  os_id uuid,
  equipamento_id uuid,
  tag text,
  titulo text,
  descricao_problema text,
  metodo_analise text,
  porque_1 text,
  porque_2 text,
  porque_3 text,
  porque_4 text,
  porque_5 text,
  causa_raiz_identificada text,
  diagrama_ishikawa jsonb,
  arvore_falhas jsonb,
  status text,
  responsavel_nome text,
  responsavel_id uuid,
  data_conclusao timestamptz,
  eficacia_verificada boolean,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.acoes_corretivas (
  id uuid primary key default gen_random_uuid(),
  rca_id uuid,
  descricao text,
  responsavel_nome text,
  responsavel_id uuid,
  prazo date,
  status text,
  data_conclusao timestamptz,
  evidencias text,
  observacoes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.melhorias (
  id uuid primary key default gen_random_uuid(),
  numero_melhoria bigint generated by default as identity,
  titulo text,
  descricao text,
  tipo text,
  area text,
  equipamento_id uuid,
  tag text,
  situacao_antes text,
  situacao_depois text,
  beneficios text,
  custo_implementacao numeric,
  economia_anual numeric,
  roi_meses integer,
  status text,
  proponente_nome text,
  proponente_id uuid,
  aprovador_nome text,
  aprovador_id uuid,
  data_aprovacao timestamptz,
  data_implementacao timestamptz,
  anexos jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.documentos_tecnicos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid,
  codigo text,
  titulo text,
  tipo text,
  tag text,
  descricao text,
  versao text,
  status text,
  arquivo_url text,
  arquivo_nome text,
  arquivo_tamanho bigint,
  data_validade date,
  data_aprovacao date,
  aprovador_id uuid,
  aprovador_nome text,
  equipamento_id uuid,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.document_sequences (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid,
  tipo_documento text,
  prefixo text,
  proximo_numero integer default 1,
  formato text,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.document_layouts (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid,
  nome text,
  tipo_documento text,
  layout_json jsonb,
  ativo boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.configuracoes_sistema (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid,
  categoria text,
  chave text,
  valor jsonb,
  descricao text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.dados_empresa (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid,
  razao_social text,
  nome_fantasia text,
  cnpj text,
  ie text,
  endereco text,
  cidade text,
  uf text,
  cep text,
  telefone text,
  email text,
  site text,
  logo_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================
-- Ajustes de colunas específicas que já deram erro no front
-- ============================================================
alter table if exists public.mecanicos add column if not exists custo_hora numeric;
alter table if exists public.materiais add column if not exists custo_unitario numeric default 0;
alter table if exists public.fornecedores add column if not exists codigo text;
alter table if exists public.planos_preventivos add column if not exists tag text;
alter table if exists public.planos_preventivos add column if not exists equipamento_id uuid;
alter table if exists public.medicoes_preditivas add column if not exists equipamento_id uuid;
alter table if exists public.solicitacoes_manutencao add column if not exists tag text;
alter table if exists public.solicitacoes_manutencao add column if not exists solicitante_nome text;
alter table if exists public.solicitacoes_manutencao add column if not exists descricao_falha text;
alter table if exists public.solicitacoes_manutencao add column if not exists status text default 'PENDENTE';

-- ============================================================
-- Índices e unicidade para estabilidade de consultas/upsert
-- ============================================================
create unique index if not exists ux_equipamentos_tag on public.equipamentos(tag);
create unique index if not exists ux_planos_preventivos_codigo on public.planos_preventivos(codigo);
create unique index if not exists ux_materiais_codigo on public.materiais(codigo);
create unique index if not exists ux_fornecedores_codigo on public.fornecedores(codigo) where codigo is not null;
create index if not exists ix_solicitacoes_status on public.solicitacoes_manutencao(status);
create index if not exists ix_ordens_servico_status on public.ordens_servico(status);
create index if not exists ix_planos_preventivos_proxima on public.planos_preventivos(proxima_execucao);

-- ============================================================
-- Triggers de updated_at
-- ============================================================
select public.ensure_updated_at_trigger('public.empresas');
select public.ensure_updated_at_trigger('public.empresa_config');
select public.ensure_updated_at_trigger('public.profiles');
select public.ensure_updated_at_trigger('public.plantas');
select public.ensure_updated_at_trigger('public.areas');
select public.ensure_updated_at_trigger('public.sistemas');
select public.ensure_updated_at_trigger('public.equipamentos');
select public.ensure_updated_at_trigger('public.ordens_servico');
select public.ensure_updated_at_trigger('public.solicitacoes_manutencao');
select public.ensure_updated_at_trigger('public.mecanicos');
select public.ensure_updated_at_trigger('public.materiais');
select public.ensure_updated_at_trigger('public.fornecedores');
select public.ensure_updated_at_trigger('public.contratos');
select public.ensure_updated_at_trigger('public.planos_preventivos');
select public.ensure_updated_at_trigger('public.atividades_preventivas');
select public.ensure_updated_at_trigger('public.servicos_preventivos');
select public.ensure_updated_at_trigger('public.inspecoes');
select public.ensure_updated_at_trigger('public.permissoes_trabalho');
select public.ensure_updated_at_trigger('public.incidentes_ssma');
select public.ensure_updated_at_trigger('public.fmea');
select public.ensure_updated_at_trigger('public.analise_causa_raiz');
select public.ensure_updated_at_trigger('public.acoes_corretivas');
select public.ensure_updated_at_trigger('public.melhorias');
select public.ensure_updated_at_trigger('public.documentos_tecnicos');
select public.ensure_updated_at_trigger('public.document_sequences');
select public.ensure_updated_at_trigger('public.document_layouts');
select public.ensure_updated_at_trigger('public.configuracoes_sistema');
select public.ensure_updated_at_trigger('public.dados_empresa');
select public.ensure_updated_at_trigger('public.maintenance_schedule');

commit;
